<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: score.proto

namespace Protoc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protoc.ChangeRequest</code>
 */
class ChangeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string action = 1;</code>
     */
    private $action = '';
    /**
     * Generated from protobuf field <code>string comment = 2;</code>
     */
    private $comment = '';
    /**
     * Generated from protobuf field <code>string company_id = 3;</code>
     */
    private $company_id = '';
    /**
     * Generated from protobuf field <code>string member_union_id = 4;</code>
     */
    private $member_union_id = '';
    /**
     * Generated from protobuf field <code>int32 score = 5;</code>
     */
    private $score = 0;
    /**
     * Generated from protobuf field <code>string created_user_id = 6;</code>
     */
    private $created_user_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $action
     *     @type string $comment
     *     @type string $company_id
     *     @type string $member_union_id
     *     @type int $score
     *     @type string $created_user_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Score::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string action = 1;</code>
     * @return string
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>string action = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string comment = 2;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Generated from protobuf field <code>string comment = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->comment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string company_id = 3;</code>
     * @return string
     */
    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Generated from protobuf field <code>string company_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->company_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_union_id = 4;</code>
     * @return string
     */
    public function getMemberUnionId()
    {
        return $this->member_union_id;
    }

    /**
     * Generated from protobuf field <code>string member_union_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberUnionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_union_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 score = 5;</code>
     * @return int
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Generated from protobuf field <code>int32 score = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkInt32($var);
        $this->score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_user_id = 6;</code>
     * @return string
     */
    public function getCreatedUserId()
    {
        return $this->created_user_id;
    }

    /**
     * Generated from protobuf field <code>string created_user_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_user_id = $var;

        return $this;
    }

}

