<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coupon.proto

namespace Protoc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protoc.ConsumingOpenCouponRequest</code>
 */
class ConsumingOpenCouponRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string stock_id = 1;</code>
     */
    protected $stock_id = '';
    /**
     * Generated from protobuf field <code>string wechat_open_coupon_code = 2;</code>
     */
    protected $wechat_open_coupon_code = '';
    /**
     * Generated from protobuf field <code>string bill_code = 3;</code>
     */
    protected $bill_code = '';
    /**
     * Generated from protobuf field <code>string user_id = 4;</code>
     */
    protected $user_id = '';
    /**
     * Generated from protobuf field <code>string shop_id = 5;</code>
     */
    protected $shop_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stock_id
     *     @type string $wechat_open_coupon_code
     *     @type string $bill_code
     *     @type string $user_id
     *     @type string $shop_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Coupon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string stock_id = 1;</code>
     * @return string
     */
    public function getStockId()
    {
        return $this->stock_id;
    }

    /**
     * Generated from protobuf field <code>string stock_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStockId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stock_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wechat_open_coupon_code = 2;</code>
     * @return string
     */
    public function getWechatOpenCouponCode()
    {
        return $this->wechat_open_coupon_code;
    }

    /**
     * Generated from protobuf field <code>string wechat_open_coupon_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWechatOpenCouponCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->wechat_open_coupon_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bill_code = 3;</code>
     * @return string
     */
    public function getBillCode()
    {
        return $this->bill_code;
    }

    /**
     * Generated from protobuf field <code>string bill_code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBillCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->bill_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_id = 4;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shop_id = 5;</code>
     * @return string
     */
    public function getShopId()
    {
        return $this->shop_id;
    }

    /**
     * Generated from protobuf field <code>string shop_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setShopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->shop_id = $var;

        return $this;
    }

}

