<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coupon.proto

namespace Protoc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protoc.ConsumingRequest</code>
 */
class ConsumingRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string coupon_code = 1;</code>
     */
    protected $coupon_code = '';
    /**
     * Generated from protobuf field <code>string member_union_id = 2;</code>
     */
    protected $member_union_id = '';
    /**
     * Generated from protobuf field <code>int32 usage = 3;</code>
     */
    protected $usage = 0;
    /**
     * Generated from protobuf field <code>string shop_id = 4;</code>
     */
    protected $shop_id = '';
    /**
     * Generated from protobuf field <code>string created_user_id = 5;</code>
     */
    protected $created_user_id = '';
    /**
     * Generated from protobuf field <code>string bill_code = 6;</code>
     */
    protected $bill_code = '';
    /**
     * Generated from protobuf field <code>repeated string product_ids = 7;</code>
     */
    private $product_ids;
    /**
     * Generated from protobuf field <code>bool is_open_coupon = 8;</code>
     */
    protected $is_open_coupon = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $coupon_code
     *     @type string $member_union_id
     *     @type int $usage
     *     @type string $shop_id
     *     @type string $created_user_id
     *     @type string $bill_code
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $product_ids
     *     @type bool $is_open_coupon
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Coupon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string coupon_code = 1;</code>
     * @return string
     */
    public function getCouponCode()
    {
        return $this->coupon_code;
    }

    /**
     * Generated from protobuf field <code>string coupon_code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCouponCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->coupon_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_union_id = 2;</code>
     * @return string
     */
    public function getMemberUnionId()
    {
        return $this->member_union_id;
    }

    /**
     * Generated from protobuf field <code>string member_union_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberUnionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_union_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 usage = 3;</code>
     * @return int
     */
    public function getUsage()
    {
        return $this->usage;
    }

    /**
     * Generated from protobuf field <code>int32 usage = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUsage($var)
    {
        GPBUtil::checkInt32($var);
        $this->usage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shop_id = 4;</code>
     * @return string
     */
    public function getShopId()
    {
        return $this->shop_id;
    }

    /**
     * Generated from protobuf field <code>string shop_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setShopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->shop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_user_id = 5;</code>
     * @return string
     */
    public function getCreatedUserId()
    {
        return $this->created_user_id;
    }

    /**
     * Generated from protobuf field <code>string created_user_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bill_code = 6;</code>
     * @return string
     */
    public function getBillCode()
    {
        return $this->bill_code;
    }

    /**
     * Generated from protobuf field <code>string bill_code = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBillCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->bill_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string product_ids = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProductIds()
    {
        return $this->product_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string product_ids = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProductIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->product_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_open_coupon = 8;</code>
     * @return bool
     */
    public function getIsOpenCoupon()
    {
        return $this->is_open_coupon;
    }

    /**
     * Generated from protobuf field <code>bool is_open_coupon = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsOpenCoupon($var)
    {
        GPBUtil::checkBool($var);
        $this->is_open_coupon = $var;

        return $this;
    }

}

