<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coupon.proto

namespace Protoc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protoc.DiscountMoneyRequest</code>
 */
class DiscountMoneyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string coupon_code = 1;</code>
     */
    private $coupon_code = '';
    /**
     * Generated from protobuf field <code>string member_union_id = 2;</code>
     */
    private $member_union_id = '';
    /**
     * Generated from protobuf field <code>int32 usage = 3;</code>
     */
    private $usage = 0;
    /**
     * Generated from protobuf field <code>int32 money = 4;</code>
     */
    private $money = 0;
    /**
     * Generated from protobuf field <code>string shop_id = 5;</code>
     */
    private $shop_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $coupon_code
     *     @type string $member_union_id
     *     @type int $usage
     *     @type int $money
     *     @type string $shop_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Coupon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string coupon_code = 1;</code>
     * @return string
     */
    public function getCouponCode()
    {
        return $this->coupon_code;
    }

    /**
     * Generated from protobuf field <code>string coupon_code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCouponCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->coupon_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_union_id = 2;</code>
     * @return string
     */
    public function getMemberUnionId()
    {
        return $this->member_union_id;
    }

    /**
     * Generated from protobuf field <code>string member_union_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberUnionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_union_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 usage = 3;</code>
     * @return int
     */
    public function getUsage()
    {
        return $this->usage;
    }

    /**
     * Generated from protobuf field <code>int32 usage = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUsage($var)
    {
        GPBUtil::checkInt32($var);
        $this->usage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 money = 4;</code>
     * @return int
     */
    public function getMoney()
    {
        return $this->money;
    }

    /**
     * Generated from protobuf field <code>int32 money = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMoney($var)
    {
        GPBUtil::checkInt32($var);
        $this->money = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shop_id = 5;</code>
     * @return string
     */
    public function getShopId()
    {
        return $this->shop_id;
    }

    /**
     * Generated from protobuf field <code>string shop_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setShopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->shop_id = $var;

        return $this;
    }

}

