<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coupon.proto

namespace Protoc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protoc.GetCountByMemberRequest</code>
 */
class GetCountByMemberRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 status = 1;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string member_union_id = 2;</code>
     */
    protected $member_union_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *     @type string $member_union_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Coupon::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_union_id = 2;</code>
     * @return string
     */
    public function getMemberUnionId()
    {
        return $this->member_union_id;
    }

    /**
     * Generated from protobuf field <code>string member_union_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberUnionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_union_id = $var;

        return $this;
    }

}

