<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: score.proto

namespace Protoc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protoc.GetMasterByMemberRequest</code>
 */
class GetMasterByMemberRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string member_union_id = 1;</code>
     */
    private $member_union_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $member_union_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Score::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string member_union_id = 1;</code>
     * @return string
     */
    public function getMemberUnionId()
    {
        return $this->member_union_id;
    }

    /**
     * Generated from protobuf field <code>string member_union_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberUnionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_union_id = $var;

        return $this;
    }

}

