<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shop.proto

namespace Protoc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protoc.GetShopsRequest</code>
 */
class GetShopsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string shopId = 1;</code>
     */
    private $shopId;
    /**
     * Generated from protobuf field <code>int32 status = 2;</code>
     */
    private $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $shopId
     *     @type int $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Shop::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string shopId = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getShopId()
    {
        return $this->shopId;
    }

    /**
     * Generated from protobuf field <code>repeated string shopId = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setShopId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->shopId = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

}

