<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: score.proto

namespace Protoc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protoc.MasterAccount</code>
 */
class MasterAccount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string master_account_id = 1;</code>
     */
    private $master_account_id = '';
    /**
     * Generated from protobuf field <code>string member_union_id = 2;</code>
     */
    private $member_union_id = '';
    /**
     * Generated from protobuf field <code>int32 total_score = 3;</code>
     */
    private $total_score = 0;
    /**
     * Generated from protobuf field <code>int32 score = 4;</code>
     */
    private $score = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $master_account_id
     *     @type string $member_union_id
     *     @type int $total_score
     *     @type int $score
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Score::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string master_account_id = 1;</code>
     * @return string
     */
    public function getMasterAccountId()
    {
        return $this->master_account_id;
    }

    /**
     * Generated from protobuf field <code>string master_account_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMasterAccountId($var)
    {
        GPBUtil::checkString($var, True);
        $this->master_account_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_union_id = 2;</code>
     * @return string
     */
    public function getMemberUnionId()
    {
        return $this->member_union_id;
    }

    /**
     * Generated from protobuf field <code>string member_union_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberUnionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_union_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total_score = 3;</code>
     * @return int
     */
    public function getTotalScore()
    {
        return $this->total_score;
    }

    /**
     * Generated from protobuf field <code>int32 total_score = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalScore($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 score = 4;</code>
     * @return int
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Generated from protobuf field <code>int32 score = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkInt32($var);
        $this->score = $var;

        return $this;
    }

}

