<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shop.proto

namespace Protoc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protoc.ShopsResult</code>
 */
class ShopsResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .protoc.Shops shops = 1;</code>
     */
    private $shops;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protoc\Shops[]|\Google\Protobuf\Internal\RepeatedField $shops
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Shop::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .protoc.Shops shops = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getShops()
    {
        return $this->shops;
    }

    /**
     * Generated from protobuf field <code>repeated .protoc.Shops shops = 1;</code>
     * @param \Protoc\Shops[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setShops($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protoc\Shops::class);
        $this->shops = $arr;

        return $this;
    }

}

