<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shop.proto

namespace Protoc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protoc.Shops</code>
 */
class Shops extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string shop_id = 2;</code>
     */
    private $shop_id = '';
    /**
     * Generated from protobuf field <code>string title = 3;</code>
     */
    private $title = '';
    /**
     * Generated from protobuf field <code>string address = 4;</code>
     */
    private $address = '';
    /**
     * Generated from protobuf field <code>string province = 5;</code>
     */
    private $province = '';
    /**
     * Generated from protobuf field <code>string city = 6;</code>
     */
    private $city = '';
    /**
     * Generated from protobuf field <code>string area = 7;</code>
     */
    private $area = '';
    /**
     * Generated from protobuf field <code>string latitude = 9;</code>
     */
    private $latitude = '';
    /**
     * Generated from protobuf field <code>string longitude = 10;</code>
     */
    private $longitude = '';
    /**
     * Generated from protobuf field <code>string poi_id = 11;</code>
     */
    private $poi_id = '';
    /**
     * Generated from protobuf field <code>string company_id = 12;</code>
     */
    private $company_id = '';
    /**
     * Generated from protobuf field <code>string phone = 13;</code>
     */
    private $phone = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $shop_id
     *     @type string $title
     *     @type string $address
     *     @type string $province
     *     @type string $city
     *     @type string $area
     *     @type string $latitude
     *     @type string $longitude
     *     @type string $poi_id
     *     @type string $company_id
     *     @type string $phone
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Shop::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shop_id = 2;</code>
     * @return string
     */
    public function getShopId()
    {
        return $this->shop_id;
    }

    /**
     * Generated from protobuf field <code>string shop_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setShopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->shop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 3;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 4;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string province = 5;</code>
     * @return string
     */
    public function getProvince()
    {
        return $this->province;
    }

    /**
     * Generated from protobuf field <code>string province = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setProvince($var)
    {
        GPBUtil::checkString($var, True);
        $this->province = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city = 6;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>string city = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string area = 7;</code>
     * @return string
     */
    public function getArea()
    {
        return $this->area;
    }

    /**
     * Generated from protobuf field <code>string area = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setArea($var)
    {
        GPBUtil::checkString($var, True);
        $this->area = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string latitude = 9;</code>
     * @return string
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Generated from protobuf field <code>string latitude = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkString($var, True);
        $this->latitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string longitude = 10;</code>
     * @return string
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Generated from protobuf field <code>string longitude = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkString($var, True);
        $this->longitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string poi_id = 11;</code>
     * @return string
     */
    public function getPoiId()
    {
        return $this->poi_id;
    }

    /**
     * Generated from protobuf field <code>string poi_id = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setPoiId($var)
    {
        GPBUtil::checkString($var, True);
        $this->poi_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string company_id = 12;</code>
     * @return string
     */
    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Generated from protobuf field <code>string company_id = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->company_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone = 13;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

}

