<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: application.proto

namespace GPBMetadata;

class Application
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abd010a116170706c69636174696f6e2e70726f746f120b6170706c6963" .
            "6174696f6e222d0a054f72646572120f0a076f726465726e6f1801200128" .
            "0912130a0b746f74616c5f6d6f6e657918022001280522180a0652657375" .
            "6c74120e0a06737461747573180120012808324a0a0b6170706c69636174" .
            "696f6e123b0a0e6170704f726465724e6f7469667912122e6170706c6963" .
            "6174696f6e2e4f726465721a132e6170706c69636174696f6e2e52657375" .
            "6c742200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

