<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: application.proto

namespace GPBMetadata;

class Application
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab4020a116170706c69636174696f6e2e70726f746f120b6170706c6963" .
            "6174696f6e222d0a054f72646572120f0a076f726465726e6f1801200128" .
            "0912130a0b746f74616c5f6d6f6e657918022001280522180a0652657375" .
            "6c74120e0a0673746174757318012001280822320a0c5075726368617365" .
            "496e666f120e0a066170705f696418012001280512120a0a636f6d70616e" .
            "795f6964180220012809328c010a0b6170706c69636174696f6e123b0a0e" .
            "6170704f726465724e6f7469667912122e6170706c69636174696f6e2e4f" .
            "726465721a132e6170706c69636174696f6e2e526573756c74220012400a" .
            "0c6175746f507572636861736512192e6170706c69636174696f6e2e5075" .
            "726368617365496e666f1a132e6170706c69636174696f6e2e526573756c" .
            "742200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

