<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authorize.proto

namespace GPBMetadata;

class Authorize
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aea020a0f617574686f72697a652e70726f746f1209617574686f72697a" .
            "65223f0a0841757468496e666f12110a09636f6d70616e79496418012001" .
            "2809120e0a0675736572496418022001280912100a08666f6c6c6f774964" .
            "180320012809221e0a0a41757468466f6c6c6f7712100a08666f6c6c6f77" .
            "496418012001280922160a0741757468426967120b0a0375696418012001" .
            "2805221a0a074964546f6b656e120f0a076964546f6b656e180120012809" .
            "32ae010a09417574686f72697a6512310a046175746812132e617574686f" .
            "72697a652e41757468496e666f1a122e617574686f72697a652e4964546f" .
            "6b656e220012390a0a61757468466f6c6c6f7712152e617574686f72697a" .
            "652e41757468466f6c6c6f771a122e617574686f72697a652e4964546f6b" .
            "656e220012330a076175746842696712122e617574686f72697a652e4175" .
            "74684269671a122e617574686f72697a652e4964546f6b656e2200620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

