<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authorize.proto

namespace GPBMetadata;

class Authorize
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0acf010a0f617574686f72697a652e70726f746f1209617574686f72697a" .
            "65224d0a0841757468496e666f12110a09636f6d70616e79496418012001" .
            "2809120c0a0474797065180220012809120e0a0675736572496418032001" .
            "280912100a08666f6c6c6f774964180420012809221a0a074964546f6b65" .
            "6e120f0a076964546f6b656e180120012809323e0a09417574686f72697a" .
            "6512310a046175746812132e617574686f72697a652e41757468496e666f" .
            "1a122e617574686f72697a652e4964546f6b656e2200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

