<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coupon.proto

namespace GPBMetadata;

class Coupon
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a88020a0c636f75706f6e2e70726f746f120670726f746f63221e0a0d44" .
            "6973636f756e744d6f6e6579120d0a056d6f6e657918012001280522730a" .
            "14446973636f756e744d6f6e65795265717565737412130a0b636f75706f" .
            "6e5f636f646518012001280912170a0f6d656d6265725f756e696f6e5f69" .
            "64180220012809120d0a057573616765180320012805120d0a056d6f6e65" .
            "79180420012805120f0a0773686f705f696418052001280932530a06436f" .
            "75706f6e12490a10476574446973636f756e744d6f6e6579121c2e70726f" .
            "746f632e446973636f756e744d6f6e6579526571756573741a152e70726f" .
            "746f632e446973636f756e744d6f6e65792200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

