<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: follow.proto

namespace GPBMetadata;

class Follow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a88030a0c666f6c6c6f772e70726f746f1206466f6c6c6f7722700a1047" .
            "6574466f6c6c6f7752657175657374120e0a066170705f69641801200128" .
            "09120e0a066f70656e696418022001280912100a08756e696f6e5f696418" .
            "032001280912130a0b69735f627573696e65737318042001280812150a0d" .
            "706c6174666f726d5f74797065180520012805223c0a1a47657442794f70" .
            "656e6964416e64417070496452657175657374120e0a066170705f696418" .
            "0120012809120e0a066f70656e6964180220012809221f0a0a466f6c6c6f" .
            "77496e666f12110a09666f6c6c6f775f69641801200128093296010a0646" .
            "6f6c6c6f77123b0a09476574466f6c6c6f7712182e466f6c6c6f772e4765" .
            "74466f6c6c6f77526571756573741a122e466f6c6c6f772e466f6c6c6f77" .
            "496e666f2200124f0a1347657442794f70656e6964416e64417070496412" .
            "222e466f6c6c6f772e47657442794f70656e6964416e6441707049645265" .
            "71756573741a122e466f6c6c6f772e466f6c6c6f77496e666f2200620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

