<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: follow.proto

namespace GPBMetadata;

class Follow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af8010a0c666f6c6c6f772e70726f746f1206466f6c6c6f7722700a1047" .
            "6574466f6c6c6f7752657175657374120e0a066170705f69641801200128" .
            "09120e0a066f70656e696418022001280912100a08756e696f6e5f696418" .
            "032001280912130a0b69735f627573696e65737318042001280812150a0d" .
            "706c6174666f726d5f74797065180520012805221f0a0a466f6c6c6f7749" .
            "6e666f12110a09666f6c6c6f775f696418012001280932450a06466f6c6c" .
            "6f77123b0a09476574466f6c6c6f7712182e466f6c6c6f772e476574466f" .
            "6c6c6f77526571756573741a122e466f6c6c6f772e466f6c6c6f77496e66" .
            "6f2200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

