<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manage.proto

namespace GPBMetadata;

class Manage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab2010a0c6d616e6167652e70726f746f12066d616e61676522230a0648" .
            "6955736572120c0a046e616d65180120012809120b0a0373657818022001" .
            "280522380a0748695265706c79120f0a076d657373616765180120012809" .
            "121c0a047573657218022001280b320e2e6d616e6167652e486955736572" .
            "32330a026869122d0a0873617948656c6c6f120e2e6d616e6167652e4869" .
            "557365721a0f2e6d616e6167652e48695265706c792200620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

