<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: application.proto

namespace Application;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>application.Order</code>
 */
class Order extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string orderno = 1;</code>
     */
    private $orderno = '';
    /**
     * Generated from protobuf field <code>int32 total_money = 2;</code>
     */
    private $total_money = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $orderno
     *     @type int $total_money
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Application::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string orderno = 1;</code>
     * @return string
     */
    public function getOrderno()
    {
        return $this->orderno;
    }

    /**
     * Generated from protobuf field <code>string orderno = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderno($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderno = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total_money = 2;</code>
     * @return int
     */
    public function getTotalMoney()
    {
        return $this->total_money;
    }

    /**
     * Generated from protobuf field <code>int32 total_money = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalMoney($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_money = $var;

        return $this;
    }

}

