<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: application.proto

namespace Application;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>application.PayOrder</code>
 */
class PayOrder extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string orderno = 1;</code>
     */
    private $orderno = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string company_id = 3;</code>
     */
    private $company_id = '';
    /**
     * Generated from protobuf field <code>int32 price = 4;</code>
     */
    private $price = 0;
    /**
     * Generated from protobuf field <code>int32 charging_model_id = 5;</code>
     */
    private $charging_model_id = 0;
    /**
     * Generated from protobuf field <code>int32 pay_mode = 6;</code>
     */
    private $pay_mode = 0;
    /**
     * Generated from protobuf field <code>int32 type = 7;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>string created_user_id = 8;</code>
     */
    private $created_user_id = '';
    /**
     * Generated from protobuf field <code>int32 package_id = 9;</code>
     */
    private $package_id = 0;
    /**
     * Generated from protobuf field <code>string payload = 10;</code>
     */
    private $payload = '';
    /**
     * Generated from protobuf field <code>string transaction_id = 11;</code>
     */
    private $transaction_id = '';
    /**
     * Generated from protobuf field <code>int32 commission = 12;</code>
     */
    private $commission = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $orderno
     *     @type string $name
     *     @type string $company_id
     *     @type int $price
     *     @type int $charging_model_id
     *     @type int $pay_mode
     *     @type int $type
     *     @type string $created_user_id
     *     @type int $package_id
     *     @type string $payload
     *     @type string $transaction_id
     *     @type int $commission
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Application::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string orderno = 1;</code>
     * @return string
     */
    public function getOrderno()
    {
        return $this->orderno;
    }

    /**
     * Generated from protobuf field <code>string orderno = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderno($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderno = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string company_id = 3;</code>
     * @return string
     */
    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Generated from protobuf field <code>string company_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->company_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 price = 4;</code>
     * @return int
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>int32 price = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkInt32($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 charging_model_id = 5;</code>
     * @return int
     */
    public function getChargingModelId()
    {
        return $this->charging_model_id;
    }

    /**
     * Generated from protobuf field <code>int32 charging_model_id = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setChargingModelId($var)
    {
        GPBUtil::checkInt32($var);
        $this->charging_model_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pay_mode = 6;</code>
     * @return int
     */
    public function getPayMode()
    {
        return $this->pay_mode;
    }

    /**
     * Generated from protobuf field <code>int32 pay_mode = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPayMode($var)
    {
        GPBUtil::checkInt32($var);
        $this->pay_mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 type = 7;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int32 type = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_user_id = 8;</code>
     * @return string
     */
    public function getCreatedUserId()
    {
        return $this->created_user_id;
    }

    /**
     * Generated from protobuf field <code>string created_user_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 package_id = 9;</code>
     * @return int
     */
    public function getPackageId()
    {
        return $this->package_id;
    }

    /**
     * Generated from protobuf field <code>int32 package_id = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setPackageId($var)
    {
        GPBUtil::checkInt32($var);
        $this->package_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payload = 10;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>string payload = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, True);
        $this->payload = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transaction_id = 11;</code>
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Generated from protobuf field <code>string transaction_id = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 commission = 12;</code>
     * @return int
     */
    public function getCommission()
    {
        return $this->commission;
    }

    /**
     * Generated from protobuf field <code>int32 commission = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setCommission($var)
    {
        GPBUtil::checkInt32($var);
        $this->commission = $var;

        return $this;
    }

}

