<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: useraccount.proto

namespace Ucenteraccount;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ucenteraccount.AccountInfo</code>
 */
class AccountInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string userId = 2;</code>
     */
    protected $userId = '';
    /**
     * Generated from protobuf field <code>uint32 balance = 3;</code>
     */
    protected $balance = 0;
    /**
     * Generated from protobuf field <code>string createdAt = 4;</code>
     */
    protected $createdAt = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $userId
     *     @type int $balance
     *     @type string $createdAt
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Useraccount::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userId = 2;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>string userId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->userId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 balance = 3;</code>
     * @return int
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     * Generated from protobuf field <code>uint32 balance = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkUint32($var);
        $this->balance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string createdAt = 4;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Generated from protobuf field <code>string createdAt = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->createdAt = $var;

        return $this;
    }

}

