<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: useraccount.proto

namespace Ucenteraccount;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ucenteraccount.ChangeRequest</code>
 */
class ChangeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string userId = 1;</code>
     */
    protected $userId = '';
    /**
     * Generated from protobuf field <code>string originType = 2;</code>
     */
    protected $originType = '';
    /**
     * Generated from protobuf field <code>string originId = 3;</code>
     */
    protected $originId = '';
    /**
     * Generated from protobuf field <code>string action = 4;</code>
     */
    protected $action = '';
    /**
     * Generated from protobuf field <code>sint32 price = 5;</code>
     */
    protected $price = 0;
    /**
     * Generated from protobuf field <code>string comment = 6;</code>
     */
    protected $comment = '';
    /**
     * Generated from protobuf field <code>string companyId = 7;</code>
     */
    protected $companyId = '';
    /**
     * Generated from protobuf field <code>.ucenteraccount.Xa xa = 8;</code>
     */
    protected $xa = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $userId
     *     @type string $originType
     *     @type string $originId
     *     @type string $action
     *     @type int $price
     *     @type string $comment
     *     @type string $companyId
     *     @type \Ucenteraccount\Xa $xa
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Useraccount::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string userId = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>string userId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->userId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string originType = 2;</code>
     * @return string
     */
    public function getOriginType()
    {
        return $this->originType;
    }

    /**
     * Generated from protobuf field <code>string originType = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginType($var)
    {
        GPBUtil::checkString($var, True);
        $this->originType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string originId = 3;</code>
     * @return string
     */
    public function getOriginId()
    {
        return $this->originId;
    }

    /**
     * Generated from protobuf field <code>string originId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginId($var)
    {
        GPBUtil::checkString($var, True);
        $this->originId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string action = 4;</code>
     * @return string
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>string action = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 price = 5;</code>
     * @return int
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>sint32 price = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkInt32($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string comment = 6;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Generated from protobuf field <code>string comment = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->comment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string companyId = 7;</code>
     * @return string
     */
    public function getCompanyId()
    {
        return $this->companyId;
    }

    /**
     * Generated from protobuf field <code>string companyId = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->companyId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ucenteraccount.Xa xa = 8;</code>
     * @return \Ucenteraccount\Xa
     */
    public function getXa()
    {
        return $this->xa;
    }

    /**
     * Generated from protobuf field <code>.ucenteraccount.Xa xa = 8;</code>
     * @param \Ucenteraccount\Xa $var
     * @return $this
     */
    public function setXa($var)
    {
        GPBUtil::checkMessage($var, \Ucenteraccount\Xa::class);
        $this->xa = $var;

        return $this;
    }

}

