<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: follow.proto

namespace Follow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Follow.FollowInfo</code>
 */
class FollowInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string follow_id = 1;</code>
     */
    private $follow_id = '';
    /**
     * Generated from protobuf field <code>bool is_business = 2;</code>
     */
    private $is_business = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $follow_id
     *     @type bool $is_business
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Follow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string follow_id = 1;</code>
     * @return string
     */
    public function getFollowId()
    {
        return $this->follow_id;
    }

    /**
     * Generated from protobuf field <code>string follow_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFollowId($var)
    {
        GPBUtil::checkString($var, True);
        $this->follow_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_business = 2;</code>
     * @return bool
     */
    public function getIsBusiness()
    {
        return $this->is_business;
    }

    /**
     * Generated from protobuf field <code>bool is_business = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsBusiness($var)
    {
        GPBUtil::checkBool($var);
        $this->is_business = $var;

        return $this;
    }

}

