<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: follow.proto

namespace Follow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Follow.FollowUnions</code>
 */
class FollowUnions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Follow.FollowUnion follow_unions = 1;</code>
     */
    private $follow_unions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Follow\FollowUnion[]|\Google\Protobuf\Internal\RepeatedField $follow_unions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Follow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Follow.FollowUnion follow_unions = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFollowUnions()
    {
        return $this->follow_unions;
    }

    /**
     * Generated from protobuf field <code>repeated .Follow.FollowUnion follow_unions = 1;</code>
     * @param \Follow\FollowUnion[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFollowUnions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Follow\FollowUnion::class);
        $this->follow_unions = $arr;

        return $this;
    }

}

