<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: follow.proto

namespace Follow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Follow.FollowList</code>
 */
class FollowList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Follow.FollowInfo follows = 1;</code>
     */
    private $follows;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Follow\FollowInfo[]|\Google\Protobuf\Internal\RepeatedField $follows
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Follow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Follow.FollowInfo follows = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFollows()
    {
        return $this->follows;
    }

    /**
     * Generated from protobuf field <code>repeated .Follow.FollowInfo follows = 1;</code>
     * @param \Follow\FollowInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFollows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Follow\FollowInfo::class);
        $this->follows = $arr;

        return $this;
    }

}

