<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: follow.proto

namespace Follow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Follow.FollowId</code>
 */
class FollowId extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string follow_id = 1;</code>
     */
    protected $follow_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $follow_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Follow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string follow_id = 1;</code>
     * @return string
     */
    public function getFollowId()
    {
        return $this->follow_id;
    }

    /**
     * Generated from protobuf field <code>string follow_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFollowId($var)
    {
        GPBUtil::checkString($var, True);
        $this->follow_id = $var;

        return $this;
    }

}

