<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/coupon.proto

namespace GPBMetadata\Protoc;

class Coupon
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae0010a1370726f746f632f636f75706f6e2e70726f746f1206636f7570" .
            "6f6e221e0a0d446973636f756e744d6f6e6579120d0a056d6f6e65791801" .
            "2001280522440a14446973636f756e744d6f6e6579526571756573741213" .
            "0a0b636f75706f6e5f636f646518012001280912170a0f6d656d6265725f" .
            "756e696f6e5f696418022001280932530a06636f75706f6e12490a104765" .
            "74446973636f756e744d6f6e6579121c2e636f75706f6e2e446973636f75" .
            "6e744d6f6e6579526571756573741a152e636f75706f6e2e446973636f75" .
            "6e744d6f6e65792200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

