<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appserv.proto

namespace Appserv;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>appserv.ConsumingRequest</code>
 */
class ConsumingRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 quantity = 1;</code>
     */
    private $quantity = 0;
    /**
     * Generated from protobuf field <code>int32 appId = 2;</code>
     */
    private $appId = 0;
    /**
     * Generated from protobuf field <code>string companyId = 3;</code>
     */
    private $companyId = '';
    /**
     * Generated from protobuf field <code>.appserv.XaRequest xa = 4;</code>
     */
    private $xa = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $quantity
     *     @type int $appId
     *     @type string $companyId
     *     @type \Appserv\XaRequest $xa
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Appserv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 1;</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 appId = 2;</code>
     * @return int
     */
    public function getAppId()
    {
        return $this->appId;
    }

    /**
     * Generated from protobuf field <code>int32 appId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkInt32($var);
        $this->appId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string companyId = 3;</code>
     * @return string
     */
    public function getCompanyId()
    {
        return $this->companyId;
    }

    /**
     * Generated from protobuf field <code>string companyId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->companyId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.appserv.XaRequest xa = 4;</code>
     * @return \Appserv\XaRequest
     */
    public function getXa()
    {
        return $this->xa;
    }

    /**
     * Generated from protobuf field <code>.appserv.XaRequest xa = 4;</code>
     * @param \Appserv\XaRequest $var
     * @return $this
     */
    public function setXa($var)
    {
        GPBUtil::checkMessage($var, \Appserv\XaRequest::class);
        $this->xa = $var;

        return $this;
    }

}

