<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Account;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>account.AccountInfo</code>
 */
class AccountInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string account_id = 1;</code>
     */
    private $account_id = '';
    /**
     * Generated from protobuf field <code>int32 balance = 2;</code>
     */
    private $balance = 0;
    /**
     * Generated from protobuf field <code>string association = 3;</code>
     */
    private $association = '';
    /**
     * Generated from protobuf field <code>int32 type = 5;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>int32 max_balance = 6;</code>
     */
    private $max_balance = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $account_id
     *     @type int $balance
     *     @type string $association
     *     @type int $type
     *     @type int $max_balance
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string account_id = 1;</code>
     * @return string
     */
    public function getAccountId()
    {
        return $this->account_id;
    }

    /**
     * Generated from protobuf field <code>string account_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountId($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 balance = 2;</code>
     * @return int
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     * Generated from protobuf field <code>int32 balance = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkInt32($var);
        $this->balance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string association = 3;</code>
     * @return string
     */
    public function getAssociation()
    {
        return $this->association;
    }

    /**
     * Generated from protobuf field <code>string association = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAssociation($var)
    {
        GPBUtil::checkString($var, True);
        $this->association = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 type = 5;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int32 type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_balance = 6;</code>
     * @return int
     */
    public function getMaxBalance()
    {
        return $this->max_balance;
    }

    /**
     * Generated from protobuf field <code>int32 max_balance = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxBalance($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_balance = $var;

        return $this;
    }

}

