<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Account;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>account.Associations</code>
 */
class Associations extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string association = 1;</code>
     */
    private $association = '';
    /**
     * Generated from protobuf field <code>int32 account_type = 2;</code>
     */
    private $account_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $association
     *     @type int $account_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string association = 1;</code>
     * @return string
     */
    public function getAssociation()
    {
        return $this->association;
    }

    /**
     * Generated from protobuf field <code>string association = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAssociation($var)
    {
        GPBUtil::checkString($var, True);
        $this->association = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 account_type = 2;</code>
     * @return int
     */
    public function getAccountType()
    {
        return $this->account_type;
    }

    /**
     * Generated from protobuf field <code>int32 account_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAccountType($var)
    {
        GPBUtil::checkInt32($var);
        $this->account_type = $var;

        return $this;
    }

}

