<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Account;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>account.BetweenRequest</code>
 */
class BetweenRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string association_id = 1;</code>
     */
    private $association_id;
    /**
     * Generated from protobuf field <code>int32 account_type = 2;</code>
     */
    private $account_type = 0;
    /**
     * Generated from protobuf field <code>int32 min_balance = 3;</code>
     */
    private $min_balance = 0;
    /**
     * Generated from protobuf field <code>int32 max_balance = 4;</code>
     */
    private $max_balance = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $association_id
     *     @type int $account_type
     *     @type int $min_balance
     *     @type int $max_balance
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string association_id = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAssociationId()
    {
        return $this->association_id;
    }

    /**
     * Generated from protobuf field <code>repeated string association_id = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAssociationId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->association_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 account_type = 2;</code>
     * @return int
     */
    public function getAccountType()
    {
        return $this->account_type;
    }

    /**
     * Generated from protobuf field <code>int32 account_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAccountType($var)
    {
        GPBUtil::checkInt32($var);
        $this->account_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 min_balance = 3;</code>
     * @return int
     */
    public function getMinBalance()
    {
        return $this->min_balance;
    }

    /**
     * Generated from protobuf field <code>int32 min_balance = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMinBalance($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_balance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_balance = 4;</code>
     * @return int
     */
    public function getMaxBalance()
    {
        return $this->max_balance;
    }

    /**
     * Generated from protobuf field <code>int32 max_balance = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxBalance($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_balance = $var;

        return $this;
    }

}

