<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Account;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>account.ChangeRequest</code>
 */
class ChangeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string account_id = 1;</code>
     */
    private $account_id = '';
    /**
     * Generated from protobuf field <code>int32 fixed_balance = 2;</code>
     */
    private $fixed_balance = 0;
    /**
     * Generated from protobuf field <code>string bill_code = 3;</code>
     */
    private $bill_code = '';
    /**
     * Generated from protobuf field <code>string bill_type = 4;</code>
     */
    private $bill_type = '';
    /**
     * Generated from protobuf field <code>string created_user_id = 5;</code>
     */
    private $created_user_id = '';
    /**
     * Generated from protobuf field <code>string created_shop_id = 6;</code>
     */
    private $created_shop_id = '';
    /**
     * Generated from protobuf field <code>string action = 7;</code>
     */
    private $action = '';
    /**
     * Generated from protobuf field <code>int32 money = 8;</code>
     */
    private $money = 0;
    /**
     * Generated from protobuf field <code>string comment = 9;</code>
     */
    private $comment = '';
    /**
     * Generated from protobuf field <code>int64 expired_time = 10;</code>
     */
    private $expired_time = 0;
    /**
     * Generated from protobuf field <code>.account.XaRequest xa = 11;</code>
     */
    private $xa = null;
    /**
     * Generated from protobuf field <code>int32 account_type = 12;</code>
     */
    private $account_type = 0;
    /**
     * Generated from protobuf field <code>string association = 13;</code>
     */
    private $association = '';
    /**
     * Generated from protobuf field <code>string company_id = 14;</code>
     */
    private $company_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $account_id
     *     @type int $fixed_balance
     *     @type string $bill_code
     *     @type string $bill_type
     *     @type string $created_user_id
     *     @type string $created_shop_id
     *     @type string $action
     *     @type int $money
     *     @type string $comment
     *     @type int|string $expired_time
     *     @type \Account\XaRequest $xa
     *     @type int $account_type
     *     @type string $association
     *     @type string $company_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string account_id = 1;</code>
     * @return string
     */
    public function getAccountId()
    {
        return $this->account_id;
    }

    /**
     * Generated from protobuf field <code>string account_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountId($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 fixed_balance = 2;</code>
     * @return int
     */
    public function getFixedBalance()
    {
        return $this->fixed_balance;
    }

    /**
     * Generated from protobuf field <code>int32 fixed_balance = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFixedBalance($var)
    {
        GPBUtil::checkInt32($var);
        $this->fixed_balance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bill_code = 3;</code>
     * @return string
     */
    public function getBillCode()
    {
        return $this->bill_code;
    }

    /**
     * Generated from protobuf field <code>string bill_code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBillCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->bill_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bill_type = 4;</code>
     * @return string
     */
    public function getBillType()
    {
        return $this->bill_type;
    }

    /**
     * Generated from protobuf field <code>string bill_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBillType($var)
    {
        GPBUtil::checkString($var, True);
        $this->bill_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_user_id = 5;</code>
     * @return string
     */
    public function getCreatedUserId()
    {
        return $this->created_user_id;
    }

    /**
     * Generated from protobuf field <code>string created_user_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_shop_id = 6;</code>
     * @return string
     */
    public function getCreatedShopId()
    {
        return $this->created_shop_id;
    }

    /**
     * Generated from protobuf field <code>string created_shop_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedShopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_shop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string action = 7;</code>
     * @return string
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>string action = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 money = 8;</code>
     * @return int
     */
    public function getMoney()
    {
        return $this->money;
    }

    /**
     * Generated from protobuf field <code>int32 money = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setMoney($var)
    {
        GPBUtil::checkInt32($var);
        $this->money = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string comment = 9;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Generated from protobuf field <code>string comment = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->comment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expired_time = 10;</code>
     * @return int|string
     */
    public function getExpiredTime()
    {
        return $this->expired_time;
    }

    /**
     * Generated from protobuf field <code>int64 expired_time = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiredTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->expired_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.account.XaRequest xa = 11;</code>
     * @return \Account\XaRequest
     */
    public function getXa()
    {
        return $this->xa;
    }

    /**
     * Generated from protobuf field <code>.account.XaRequest xa = 11;</code>
     * @param \Account\XaRequest $var
     * @return $this
     */
    public function setXa($var)
    {
        GPBUtil::checkMessage($var, \Account\XaRequest::class);
        $this->xa = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 account_type = 12;</code>
     * @return int
     */
    public function getAccountType()
    {
        return $this->account_type;
    }

    /**
     * Generated from protobuf field <code>int32 account_type = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setAccountType($var)
    {
        GPBUtil::checkInt32($var);
        $this->account_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string association = 13;</code>
     * @return string
     */
    public function getAssociation()
    {
        return $this->association;
    }

    /**
     * Generated from protobuf field <code>string association = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setAssociation($var)
    {
        GPBUtil::checkString($var, True);
        $this->association = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string company_id = 14;</code>
     * @return string
     */
    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Generated from protobuf field <code>string company_id = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->company_id = $var;

        return $this;
    }

}

