<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Account;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>account.CreatesRequest</code>
 */
class CreatesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .account.CreateRequest creates = 1;</code>
     */
    private $creates;
    /**
     * Generated from protobuf field <code>.account.XaRequest xa = 2;</code>
     */
    private $xa = null;
    /**
     * Generated from protobuf field <code>string company_id = 3;</code>
     */
    private $company_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Account\CreateRequest[]|\Google\Protobuf\Internal\RepeatedField $creates
     *     @type \Account\XaRequest $xa
     *     @type string $company_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .account.CreateRequest creates = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCreates()
    {
        return $this->creates;
    }

    /**
     * Generated from protobuf field <code>repeated .account.CreateRequest creates = 1;</code>
     * @param \Account\CreateRequest[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCreates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Account\CreateRequest::class);
        $this->creates = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.account.XaRequest xa = 2;</code>
     * @return \Account\XaRequest
     */
    public function getXa()
    {
        return $this->xa;
    }

    /**
     * Generated from protobuf field <code>.account.XaRequest xa = 2;</code>
     * @param \Account\XaRequest $var
     * @return $this
     */
    public function setXa($var)
    {
        GPBUtil::checkMessage($var, \Account\XaRequest::class);
        $this->xa = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string company_id = 3;</code>
     * @return string
     */
    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Generated from protobuf field <code>string company_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->company_id = $var;

        return $this;
    }

}

