<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Account;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>account.Total</code>
 */
class Total extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double total = 1;</code>
     */
    private $total = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $total
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double total = 1;</code>
     * @return float
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>double total = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkDouble($var);
        $this->total = $var;

        return $this;
    }

}

