<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authorize.proto

namespace Authorize;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authorize.AuthBig</code>
 */
class AuthBig extends \Google\Protobuf\Internal\Message
{
    /**
     * 粉丝id
     *
     * Generated from protobuf field <code>int32 uid = 1;</code>
     */
    private $uid = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $uid
     *           粉丝id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authorize::initOnce();
        parent::__construct($data);
    }

    /**
     * 粉丝id
     *
     * Generated from protobuf field <code>int32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * 粉丝id
     *
     * Generated from protobuf field <code>int32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkInt32($var);
        $this->uid = $var;

        return $this;
    }

}

