<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authorize.proto

namespace Authorize;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authorize.AuthFollow</code>
 */
class AuthFollow extends \Google\Protobuf\Internal\Message
{
    /**
     * 粉丝id
     *
     * Generated from protobuf field <code>string followId = 1;</code>
     */
    private $followId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $followId
     *           粉丝id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Authorize::initOnce();
        parent::__construct($data);
    }

    /**
     * 粉丝id
     *
     * Generated from protobuf field <code>string followId = 1;</code>
     * @return string
     */
    public function getFollowId()
    {
        return $this->followId;
    }

    /**
     * 粉丝id
     *
     * Generated from protobuf field <code>string followId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFollowId($var)
    {
        GPBUtil::checkString($var, True);
        $this->followId = $var;

        return $this;
    }

}

