<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member.proto

namespace Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>member.GetByMemberUnionIds</code>
 */
class GetByMemberUnionIds extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string union_ids = 1;</code>
     */
    private $union_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $union_ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string union_ids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnionIds()
    {
        return $this->union_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string union_ids = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnionIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->union_ids = $arr;

        return $this;
    }

}

