<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member.proto

namespace Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>member.MembersCards</code>
 */
class MembersCards extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .member.MemberCards member_cards = 1;</code>
     */
    private $member_cards;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Member\MemberCards[]|\Google\Protobuf\Internal\RepeatedField $member_cards
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .member.MemberCards member_cards = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMemberCards()
    {
        return $this->member_cards;
    }

    /**
     * Generated from protobuf field <code>repeated .member.MemberCards member_cards = 1;</code>
     * @param \Member\MemberCards[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMemberCards($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Member\MemberCards::class);
        $this->member_cards = $arr;

        return $this;
    }

}

