<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member.proto

namespace Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>member.MemberInfo</code>
 */
class MemberInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string nickname = 2;</code>
     */
    private $nickname = '';
    /**
     * Generated from protobuf field <code>string openid = 3;</code>
     */
    private $openid = '';
    /**
     * Generated from protobuf field <code>string union_id = 4;</code>
     */
    private $union_id = '';
    /**
     * Generated from protobuf field <code>string headimgurl = 5;</code>
     */
    private $headimgurl = '';
    /**
     * Generated from protobuf field <code>string follow_id = 6;</code>
     */
    private $follow_id = '';
    /**
     * Generated from protobuf field <code>string mobile = 7;</code>
     */
    private $mobile = '';
    /**
     * Generated from protobuf field <code>string full_name = 8;</code>
     */
    private $full_name = '';
    /**
     * Generated from protobuf field <code>string company_id = 9;</code>
     */
    private $company_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $nickname
     *     @type string $openid
     *     @type string $union_id
     *     @type string $headimgurl
     *     @type string $follow_id
     *     @type string $mobile
     *     @type string $full_name
     *     @type string $company_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nickname = 2;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * Generated from protobuf field <code>string nickname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string openid = 3;</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     * Generated from protobuf field <code>string openid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string union_id = 4;</code>
     * @return string
     */
    public function getUnionId()
    {
        return $this->union_id;
    }

    /**
     * Generated from protobuf field <code>string union_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUnionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->union_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string headimgurl = 5;</code>
     * @return string
     */
    public function getHeadimgurl()
    {
        return $this->headimgurl;
    }

    /**
     * Generated from protobuf field <code>string headimgurl = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setHeadimgurl($var)
    {
        GPBUtil::checkString($var, True);
        $this->headimgurl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string follow_id = 6;</code>
     * @return string
     */
    public function getFollowId()
    {
        return $this->follow_id;
    }

    /**
     * Generated from protobuf field <code>string follow_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFollowId($var)
    {
        GPBUtil::checkString($var, True);
        $this->follow_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mobile = 7;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * Generated from protobuf field <code>string mobile = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string full_name = 8;</code>
     * @return string
     */
    public function getFullName()
    {
        return $this->full_name;
    }

    /**
     * Generated from protobuf field <code>string full_name = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setFullName($var)
    {
        GPBUtil::checkString($var, True);
        $this->full_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string company_id = 9;</code>
     * @return string
     */
    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Generated from protobuf field <code>string company_id = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->company_id = $var;

        return $this;
    }

}

