<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member.proto

namespace Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>member.MemberCards</code>
 */
class MemberCards extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string nickname = 2;</code>
     */
    private $nickname = '';
    /**
     * Generated from protobuf field <code>string openid = 3;</code>
     */
    private $openid = '';
    /**
     * Generated from protobuf field <code>string union_id = 4;</code>
     */
    private $union_id = '';
    /**
     * Generated from protobuf field <code>string headimgurl = 5;</code>
     */
    private $headimgurl = '';
    /**
     * Generated from protobuf field <code>string follow_id = 6;</code>
     */
    private $follow_id = '';
    /**
     * Generated from protobuf field <code>repeated .member.Card cards = 7;</code>
     */
    private $cards;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $nickname
     *     @type string $openid
     *     @type string $union_id
     *     @type string $headimgurl
     *     @type string $follow_id
     *     @type \Member\Card[]|\Google\Protobuf\Internal\RepeatedField $cards
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nickname = 2;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * Generated from protobuf field <code>string nickname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string openid = 3;</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     * Generated from protobuf field <code>string openid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string union_id = 4;</code>
     * @return string
     */
    public function getUnionId()
    {
        return $this->union_id;
    }

    /**
     * Generated from protobuf field <code>string union_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUnionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->union_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string headimgurl = 5;</code>
     * @return string
     */
    public function getHeadimgurl()
    {
        return $this->headimgurl;
    }

    /**
     * Generated from protobuf field <code>string headimgurl = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setHeadimgurl($var)
    {
        GPBUtil::checkString($var, True);
        $this->headimgurl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string follow_id = 6;</code>
     * @return string
     */
    public function getFollowId()
    {
        return $this->follow_id;
    }

    /**
     * Generated from protobuf field <code>string follow_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFollowId($var)
    {
        GPBUtil::checkString($var, True);
        $this->follow_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .member.Card cards = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCards()
    {
        return $this->cards;
    }

    /**
     * Generated from protobuf field <code>repeated .member.Card cards = 7;</code>
     * @param \Member\Card[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCards($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Member\Card::class);
        $this->cards = $arr;

        return $this;
    }

}

